### ISSUE TITLE
Inconsistent executions

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#155] opened 2016-09-09 13:28 UTC
I have been testing the FCU pilot with app 2.0.0 and have encountered some odd, non-repeatable behaviours. Some simulation runs either don't produce output from FMUs, sometimes give NaN warnings on initial variables, and other times work without error. I make no changes between simulations other than sometimes changing the variables to live stream. Unfortunately I can't repeat this - are logs stored anywhere where I could find the errors to send them?

**Comment by richardpayne** [comment] 2016-09-09 14:03
I have worked out a series of actions that causes this result. 

Using the FCU example in Github, run 4-model multi model as normal. This produces a graph like this (as expected): 

![screenshot 2016-09-09 14 55 47](https://cloud.githubusercontent.com/assets/5848867/18389483/0b2a189c-769e-11e6-9158-b2911a7d5fd0.png)

Then, if we change the 'controllerFrequency' parameter of the controllerFMU to '10000000000' and start simulation, we get an exception: 

![screenshot 2016-09-09 14 34 32](https://cloud.githubusercontent.com/assets/5848867/18389519/34d3e42a-769e-11e6-9654-0265a26e302f.png)
 
Changing the 'controllerFrequency' parameter of the controllerFMU back to '1000000000' and resimulating (without closing the app) gives this result: 

![screenshot 2016-09-09 14 57 33](https://cloud.githubusercontent.com/assets/5848867/18389549/55e9bc34-769e-11e6-9ff8-f811bb6fb7ae.png)

simulating for a third time, without doing anything, gives this result:

![screenshot 2016-09-09 15 00 04](https://cloud.githubusercontent.com/assets/5848867/18389558/62c4aa9a-769e-11e6-9bf5-43fd80a57507.png)

Each time the Environment FMU is not outputting values, first on the RAT_out port and secondly on the OAT_out port.

**Comment by ldcouto** [comment] 2016-09-21 11:33
Seems like an issue with the COE, primarily. Do the log.csv files confirm what you're seeing in the app plot? IE, the RAT_out value is missing, etc?

**Comment by richardpayne** [comment] 2016-09-22 10:46
Yeah, the log.csv file just has output values for the environment as 0.

**Comment by lausdahl** [comment] 2016-10-24 20:47
1. please do not include pictures of the console output of the COE copy the text. The only part not visible is the one I need.
2. your experiment is faulty. Only the first run is valid. You need to clean your system completely after such a hard crash. There might be an old COE hanging that has shared memory connected to the still running FMU. If you then reload the FMU but end up connecting to the already running FMU from the hard crash then the behaviour is undefined. (We know that his can happen and will eventually fix it, but until please clean up after the crash)
3. if you calculate initial values for ports then make sure you dont need them before the controller actually have had enough time to calculate them, just mentioning this because Martin had an issue about this reported earlier.

**Comment by richardpayne** [comment] 2016-10-25 10:48
1. Ok! :) The steps I gave recreate this bug.
2. I agree - the point I was making is that after such a crash (the cause of which is not obvious at all), the behaviour of the COE was totally unexpected. Perhaps some instructions are needed for users at this point - e.g. what should a user do to 'clean your system'?
3. Ok.

**Comment by ldcouto** [comment] 2016-11-26 21:46
What's the sstatus on this?

**Comment by lausdahl** [comment] 2016-11-29 10:52
No progress have been made but we know that the system can be cleaned by terminating the COE and the Overture FMUs.

On Mac one can terminate the Overture FMUs like this:
```bash
ps aux | grep --color=never ShmServer | awk '{print \$2}' | xargs kill -9
```

and on windows a more rough shutdown can be done with (it kills all Java):

```bash
taskkill /f /im java.exe
```

**Comment by ldcouto** [comment] 2017-01-06 11:50
I've been replaying this issue with the current FCU example. I used the 3-model example since 4-model was dropped. The problem is still there but it's changed slightly. 

To reproduce this:
1. run 3-model co-simulation. everything works fine
2. change frequency to 1000000000 and rerun. co-simulation crashes. this part is probably related to #158 
3. revert frequency to 1000000000 and rerun. co-simulation crashes in a different point (previously, it ran to completion). If you keep retrying, it always crashes (previously, you would get a different result)

The root cause is the well-known problem with crashes in Overture FMUs polluting the memory space (as Kenneth explained above). We will use this issue to track progress on this. And continue to mention the workaround in the release notes.

**Comment by lausdahl** [comment] 2017-01-13 23:00
Can you please retry with Overture FMU 0.1.6. It should contain a mechanism to clean up the system once unloaded from the COE. This does not fix the crash but it should make sure that the simulations are consistent.

**Comment by richardpayne** [comment] 2017-01-31 12:24
Retried this - and now get different behaviours. I've copied the log below. Here when following the steps outlined by Luis, when I get to step 3, I get incorrect results. Repeating simulation causes the crash below. The COE quits at this stage.

Overview
Console
Terminal args: java -jar /Users/nrjp6/Library/Application Support/INTO-CPS APP/intoCpsApp/tmp/install_temp/coe.jar
COE(Command line options: [port]
Version: 0.1.10
Now running on port 8082
INFO [NanoHttpd Request Processor (#1)] (RequestProcessors.java:160) - Using Fixed-step size calculator with size = 1.0
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:44) - loading fmus
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {controllerFMU}.controller = Set(valveOpen, fanSpeed)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {roomheatingFMU}.room = Set(RAT)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {environmentFMU}.env = Set(RAT_OUT, OAT_OUT)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:267) - Inputs for: {controllerFMU}.controller
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {environmentFMU}.env.RAT_OUT --> RATSP
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {roomheatingFMU}.room.RAT --> RAT
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:267) - Inputs for: {roomheatingFMU}.room
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {environmentFMU}.env.OAT_OUT --> OAT
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {controllerFMU}.controller.valveOpen --> valveopen
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {controllerFMU}.controller.fanSpeed --> fanspeed
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'FCUController_Limited', GUID: '{9f720072-e5ec-4958-80e3-1362604bc0b4}', Vendor tool: 'Overture', Generated by: 'Overture Tool FMI Exporter - v0.1.6', at: 2017-01-31T11:27:57 Execution tool required: true
WARN [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:388) - Make sure the execution tool: 'Overture' is available during this simulation.
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'RoomHeating', GUID: '{c2d275e0-33c1-48ef-88e0-66c4daa921d0}', Vendor tool: '', Generated by: '20-sim', at: Execution tool required: false
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'Environment', GUID: '{69387efb-46a9-47b0-86dd-cd23e13586f9}', Vendor tool: '', Generated by: '20-sim', at: Execution tool required: false
INFO [NanoHttpd Request Processor (#1)] (BasicInitializer.java:242) - Initialization complete
INFO [NanoHttpd Request Processor (#1)] (Coe.scala:82) - Simulated in 00:01:53,824
INFO [NanoHttpd Request Processor (#1)] (Coe.scala:93) - Total global simulations performed: 1
No alive signal from FMU withing 800 ms period. Freeing instance!
WARN [Thread-2] (ProtocolDriver.java:102) - No alive signal from FMU withing 800 ms period. Freeing instance!
INFO [NanoHttpd Request Processor (#1)] (RequestProcessors.java:160) - Using Fixed-step size calculator with size = 1.0
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:44) - loading fmus
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {controllerFMU}.controller = Set(valveOpen, fanSpeed)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {roomheatingFMU}.room = Set(RAT)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {environmentFMU}.env = Set(RAT_OUT, OAT_OUT)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:267) - Inputs for: {controllerFMU}.controller
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {environmentFMU}.env.RAT_OUT --> RATSP
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {roomheatingFMU}.room.RAT --> RAT
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:267) - Inputs for: {roomheatingFMU}.room
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {environmentFMU}.env.OAT_OUT --> OAT
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {controllerFMU}.controller.valveOpen --> valveopen
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {controllerFMU}.controller.fanSpeed --> fanspeed
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'FCUController_Limited', GUID: '{9f720072-e5ec-4958-80e3-1362604bc0b4}', Vendor tool: 'Overture', Generated by: 'Overture Tool FMI Exporter - v0.1.6', at: 2017-01-31T11:27:57 Execution tool required: true
WARN [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:388) - Make sure the execution tool: 'Overture' is available during this simulation.
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'RoomHeating', GUID: '{c2d275e0-33c1-48ef-88e0-66c4daa921d0}', Vendor tool: '', Generated by: '20-sim', at: Execution tool required: false
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'Environment', GUID: '{69387efb-46a9-47b0-86dd-cd23e13586f9}', Vendor tool: '', Generated by: '20-sim', at: Execution tool required: false
ERROR [NanoHttpd Request Processor (#1)] (RequestProcessors.java:324) - Error in simulation
java.lang.ArrayStoreException
at java.util.ArrayList.toArray(ArrayList.java:407)
at org.intocps.orchestration.coe.util.Util.setRaw(Util.java:103)
at org.intocps.orchestration.coe.util.Util.setRaw(Util.java:85)
at org.intocps.orchestration.coe.BasicInitializer$FmiStateCache.synchroniseInstances(BasicInitializer.java:88)
at org.intocps.orchestration.coe.BasicInitializer.initialize(BasicInitializer.java:169)
at org.intocps.orchestration.coe.scala.CoeSimulator$.simulate(CoeSimulator.scala:62)
at org.intocps.orchestration.coe.scala.Coe.simulate(Coe.scala:79)
at org.intocps.orchestration.coe.httpserver.RequestProcessors.processSimulate(RequestProcessors.java:320)
at org.intocps.orchestration.coe.httpserver.RequestHandler.simulate(RequestHandler.java:282)
at org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest(RequestHandler.java:181)
at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:36)
at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:925)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Thread.java:745)
INFO [NanoHttpd Request Processor (#1)] (RequestProcessors.java:160) - Using Fixed-step size calculator with size = 1.0
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:44) - loading fmus
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {controllerFMU}.controller = Set(valveOpen, fanSpeed)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {roomheatingFMU}.room = Set(RAT)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {environmentFMU}.env = Set(RAT_OUT, OAT_OUT)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:267) - Inputs for: {controllerFMU}.controller
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {environmentFMU}.env.RAT_OUT --> RATSP
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {roomheatingFMU}.room.RAT --> RAT
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:267) - Inputs for: {roomheatingFMU}.room
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {environmentFMU}.env.OAT_OUT --> OAT
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {controllerFMU}.controller.valveOpen --> valveopen
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {controllerFMU}.controller.fanSpeed --> fanspeed
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'FCUController_Limited', GUID: '{9f720072-e5ec-4958-80e3-1362604bc0b4}', Vendor tool: 'Overture', Generated by: 'Overture Tool FMI Exporter - v0.1.6', at: 2017-01-31T11:27:57 Execution tool required: true
WARN [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:388) - Make sure the execution tool: 'Overture' is available during this simulation.
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'RoomHeating', GUID: '{c2d275e0-33c1-48ef-88e0-66c4daa921d0}', Vendor tool: '', Generated by: '20-sim', at: Execution tool required: false
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'Environment', GUID: '{69387efb-46a9-47b0-86dd-cd23e13586f9}', Vendor tool: '', Generated by: '20-sim', at: Execution tool required: false
INFO [NanoHttpd Request Processor (#1)] (BasicInitializer.java:242) - Initialization complete
INFO [NanoHttpd Request Processor (#1)] (Coe.scala:82) - Simulated in 00:01:33,150
INFO [NanoHttpd Request Processor (#1)] (Coe.scala:93) - Total global simulations performed: 2
No alive signal from FMU withing 800 ms period. Freeing instance!
WARN [Thread-2] (ProtocolDriver.java:102) - No alive signal from FMU withing 800 ms period. Freeing instance!
INFO [NanoHttpd Request Processor (#1)] (RequestProcessors.java:160) - Using Fixed-step size calculator with size = 1.0
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:44) - loading fmus
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {controllerFMU}.controller = Set(valveOpen, fanSpeed)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {roomheatingFMU}.room = Set(RAT)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:261) - Outputs from: {environmentFMU}.env = Set(RAT_OUT, OAT_OUT)
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:267) - Inputs for: {controllerFMU}.controller
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {environmentFMU}.env.RAT_OUT --> RATSP
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {roomheatingFMU}.room.RAT --> RAT
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:267) - Inputs for: {roomheatingFMU}.room
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {environmentFMU}.env.OAT_OUT --> OAT
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {controllerFMU}.controller.valveOpen --> valveopen
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:269) - {controllerFMU}.controller.fanSpeed --> fanspeed
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'FCUController_Limited', GUID: '{9f720072-e5ec-4958-80e3-1362604bc0b4}', Vendor tool: 'Overture', Generated by: 'Overture Tool FMI Exporter - v0.1.6', at: 2017-01-31T11:27:57 Execution tool required: true
WARN [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:388) - Make sure the execution tool: 'Overture' is available during this simulation.
INFO [NanoHttpd Request Processor (#1)] (CoeInitialize.scala:384) - Instantiating FMU. ModelName: 'RoomHeating', GUID: '{c2d275e0-33c1-48ef-88e0-66c4daa921d0}', Vendor tool: '', Generated by: '20-sim', at: Execution tool required: false
java(3184,0x70000980b000) malloc: *** error for object 0x7f97539ef9e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
No alive signal from FMU withing 800 ms period. Freeing instance!
WARN [Thread-2] (ProtocolDriver.java:102) - No alive signal from FMU withing 800 ms period. Freeing instance!
No alive signal from FMU withing 800 ms period. Freeing instance!
WARN [Thread-2] (ProtocolDriver.java:102) - No alive signal from FMU withing 800 ms period. Freeing instance!

**Comment by lausdahl** [comment] 2017-02-16 10:04
I think the model should be fixed. Please remove the Overture FMU and used the newest exporter to export it. The model inside the controller limited fmu is no longer valid. So the FMU must be an old version.


I fixed altered the FMU and re-exported and could not reproduce it.

**Comment by ldcouto** [comment] 2017-02-16 10:18
@lausdahl , you're saying you confirmed that crashed FMUs with the new exporter no longer corrupt the memory space?

**Comment by lausdahl** [comment] 2017-02-16 12:26
Yes the last to versions did not do that. So it is not a problem with overture.

**Comment by ldcouto** [comment] 2017-02-16 12:29
Alright, closing this issue and dropping it from future meeting notes. @richardpayne , please use #158 to track further work on this.

**Closed by ldcouto** 2017-02-16 12:29 UTC
Labels: bug, unable-to-reproduce

**Comment by lausdahl** [comment] 2017-02-16 12:30
I did a little further investigation and it actually seems like it all works as expected from the VDM side. Not really sure what the intended behaviour from an FMI point of view is suppose to be.

The issue with this model is the encoding of the continues environment it is none deterministic. With the new stop feature in the app I can make it crash after 20 or so repeats, but the fault is not in Overture look below. The environment sends NaN to Overture which it then kindly lets to COE know that it cannot handle.

```bash
INFO [NanoHttpd Request Processor (#15)] (BasicInitializer.java:242) - Initialization complete
TRACE [NanoHttpd Request Processor (#15)] (Util.java:145) - getRaw Real, comp: {d6f79f1a-a091-49d6-8d5f-128ba71eece0}.controller indices: [3, 4]
TRACE [NanoHttpd Request Processor (#15)] (Util.java:181) - getRaw Real, comp: {d6f79f1a-a091-49d6-8d5f-128ba71eece0}.controller indices: [3, 4] got values: [0.0, 0.0]
TRACE [NanoHttpd Request Processor (#15)] (Util.java:145) - getRaw Real, comp: {c2d275e0-33c1-48ef-88e0-66c4daa921d0}.room indices: [34]
TRACE [NanoHttpd Request Processor (#15)] (Util.java:181) - getRaw Real, comp: {c2d275e0-33c1-48ef-88e0-66c4daa921d0}.room indices: [34] got values: [16.0]
TRACE [NanoHttpd Request Processor (#15)] (Util.java:145) - getRaw Real, comp: {69387efb-46a9-47b0-86dd-cd23e13586f9}.env indices: [23, 24]
TRACE [NanoHttpd Request Processor (#15)] (Util.java:181) - getRaw Real, comp: {69387efb-46a9-47b0-86dd-cd23e13586f9}.env indices: [23, 24] got values: [6.11, NaN]
DEBUG [NanoHttpd Request Processor (#15)] (ResultLogger.scala:40) - Starting logger with file: 9653c5d7-56fd-4c4c-94cf-88a326b7c9f9/outputs.csv
TRACE [NanoHttpd Request Processor (#15)] (ResultLogger.scala:44) - org.intocps.orchestration.coe.scala.CoeObject$GlobalState@594a0e2d
TRACE [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:147) - Estimate derivatives to min order 2
TRACE [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:150) - Resolving inputs for doStep
TRACE [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:153) - Setting inputs
TRACE [NanoHttpd Request Processor (#15)] (Util.java:93) - setRaw with comp: {d6f79f1a-a091-49d6-8d5f-128ba71eece0}.controller, type: Real, indices: [1, 2], values: [NaN, 16.0]
TRACE [NanoHttpd Request Processor (#15)] (Util.java:114) - setRaw complete. Type='Real', indices [1, 2] values [NaN, 16.0] Status returned='OK'
TRACE [NanoHttpd Request Processor (#15)] (Util.java:93) - setRaw with comp: {c2d275e0-33c1-48ef-88e0-66c4daa921d0}.room, type: Real, indices: [32, 33, 35], values: [0.0, 6.11, 0.0]
TRACE [NanoHttpd Request Processor (#15)] (Util.java:114) - setRaw complete. Type='Real', indices [32, 33, 35] values [0.0, 6.11, 0.0] Status returned='OK'
TRACE [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:158) - Calculating step-size
TRACE [NanoHttpd Request Processor (#15)] (BasicFixedStepSizeCalculator.scala:26) - Calculating the stepsize for the fixed step size calculator
TRACE [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:303) - Calling doStep
TRACE [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:319) - DoStep on 'controller' currentCommunicationPoint: 0.0 communicationStepSize: 1.0
ERROR [Thread-61979] (CoeInitialize.scala:399) - logError Error controller Error in DoStep: Infinite or NaN trouble
TRACE [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:319) - DoStep on 'room' currentCommunicationPoint: 0.0 communicationStepSize: 1.0
TRACE [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:319) - DoStep on 'env' currentCommunicationPoint: 0.0 communicationStepSize: 1.0
DEBUG [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:503) - Calling terminate for: {controllerFMU}.controller
INFO [Thread-61980] (CoeInitialize.scala:398) - logAll OK controller terminate
DEBUG [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:503) - Calling terminate for: {roomheatingFMU}.room
DEBUG [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:503) - Calling terminate for: {environmentFMU}.env
DEBUG [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:518) - Calling freeInstance for: {controllerFMU}.controller
org.overture.interpreter.runtime.ValueException: Infinite or NaN trouble
at org.overture.interpreter.values.NumericValue.valueOf(NumericValue.java:54)
at org.crescendo.fmi.StateCache.collectInputsFromCache(StateCache.java:111)
at org.crescendo.fmi.CrescendoFmu.DoStep(CrescendoFmu.java:185)
at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:200)
at java.lang.Thread.run(Thread.java:745)
DEBUG [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:518) - Calling freeInstance for: {roomheatingFMU}.room
DEBUG [NanoHttpd Request Processor (#15)] (CoeSimulator.scala:518) - Calling freeInstance for: {environmentFMU}.env
DEBUG [NanoHttpd Request Processor (#15)] (Fmu.java:146) - UnLoad FMU /Users/kel/data/into-cps/case-studies/case-study_fcu/FMUs/Environment.fmu, temp folder
DEBUG [NanoHttpd Request Processor (#15)] (Fmu.java:152) - Deleting temp folder /var/folders/vz/fynyp6h16cj6cxrfkgjnk49h0000gn/T/Environment3738770561855488057
DEBUG [NanoHttpd Request Processor (#15)] (Fmu.java:146) - UnLoad FMU /Users/kel/data/into-cps/case-studies/case-study_fcu/FMUs/RoomHeating.fmu, temp folder
DEBUG [NanoHttpd Request Processor (#15)] (Fmu.java:152) - Deleting temp folder /var/folders/vz/fynyp6h16cj6cxrfkgjnk49h0000gn/T/RoomHeating4201104741844061028
DEBUG [NanoHttpd Request Processor (#15)] (Fmu.java:146) - UnLoad FMU /Users/kel/data/into-cps/case-studies/case-study_fcu/FMUs/controller.fmu, temp folder
DEBUG [NanoHttpd Request Processor (#15)] (Fmu.java:152) - Deleting temp folder /var/folders/vz/fynyp6h16cj6cxrfkgjnk49h0000gn/T/controller7370054627820933768
ERROR [NanoHttpd Request Processor (#15)] (RequestProcessors.java:347) - Error in simulation
org.intocps.orchestration.coe.AbortSimulationException: Fatal simulation error. Stopping simulation NOW!. Status: 
at org.intocps.orchestration.coe.scala.CoeSimulator$.doStep(CoeSimulator.scala:340)
at org.intocps.orchestration.coe.scala.CoeSimulator$.doIntermediateSimulationStep(CoeSimulator.scala:195)
at org.intocps.orchestration.coe.scala.CoeSimulator$.doSimulationStep(CoeSimulator.scala:164)
at org.intocps.orchestration.coe.scala.CoeSimulator$.simulate(CoeSimulator.scala:69)
at org.intocps.orchestration.coe.scala.Coe.simulate(Coe.scala:92)
at org.intocps.orchestration.coe.httpserver.RequestProcessors.simulate(RequestProcessors.java:343)
at org.intocps.orchestration.coe.httpserver.RequestProcessors.processSimulate(RequestProcessors.java:370)
at org.intocps.orchestration.coe.httpserver.RequestHandler.simulate(RequestHandler.java:294)
at org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest(RequestHandler.java:187)
at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:36)
at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:925)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Thread.java:745)
No alive signal from FMU withing 800 ms period. Freeing instance!
WARN [Thread-2] (ProtocolDriver.java:102) - No alive signal from FMU withing 800 ms period. Freeing instance!
```

so make sure the env is deterministic and does not occasionally send NaN seems like the proper fix.

**Comment by lausdahl** [comment] 2017-02-16 12:31
@richardpayne @ldcouto you should probably report this to CLP it looks like a 20sim model
