### ISSUE TITLE
Report an issue points to 404

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#134] opened 2016-07-26 10:25 UTC
Using the 'Report Issue' menu option brings a pop up window with a GitHub 404.

It seems to direct to https://github.com/into-cps/INTO-CPS_Application/issues/new

**Comment by ldcouto** [comment] 2016-07-27 08:22
Duplicate of #124. Already fixed.

**Closed by ldcouto** 2016-07-27 08:22 UTC
