### ISSUE TITLE
Validate HTML

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#25] opened 2016-04-27 10:43 UTC
As part of the copy-html task, we should validate it. There's some gulp plugins for it: 
* https://www.npmjs.com/package/gulp-html-validator
* https://www.npmjs.com/package/gulp-htmlhint

**Comment by ldcouto** [comment] 2016-06-15 07:46
Ok, I have a validator in place. It fails the task when html is invalid. See below:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: 3 errors found in C:\Users\CoutoLD\dev\intocps-ui\src\main.html
[L1:C1] Doctype must be declared first. (doctype-first)
[L3:C25] Special characters must be escaped : [ > ]. (spec-char-escape)
[L3:C32] The value of attribute [ id ] must be in double quotes. (attr-value-double-quote
```

We have some violations reported at the moment. I'll track them on this issue

**Comment by ldcouto** [comment] 2016-06-15 09:16
@FlorianLapschies I've fixed some HTML violations in the RTT pages (you can check this with `gulp valid`. Most of it was small stuff but I did rename some element IDs so if you could double check that it's correct, I'd appreciate it.

**Comment by ldcouto** [comment] 2016-06-15 09:19
@CThuleHansen @lausdahl the coe.html has 5 violations due to repeated ids. I think these are all related to the edit buttons and text labels for co-sim start time, etc.

This looks like an attempt at making a generic UI element so maybe we can move it into another document and embed that?

I want to have HTML violations failing the build so we need to fix this.

**Comment by CThuleHansen** [comment] 2016-06-15 09:28
Moving it to another document would fix the error, but not the cause.
Duplicate ids are not allowed globally (standardized).

However, I think we can allow violations of the standard.
Your solution would fix the error reported, because the checker is "dumb" (I think).

We will make the checker happy. :)

**Comment by ldcouto** [comment] 2016-06-15 11:43
We can disable that specific check but I'd rather not. In some cases (jquery lookups) it could actually be helpful. 

I guess another solution is to change the id to a class.

I've seem some places state that ids need only be unique cross documents but I haven't confirmed either way.

**Comment by CThuleHansen** [comment] 2016-06-15 11:44
I believe the standard states that It always has to be unique in the document . So if 2 pages are not loaded at the same time, then they can use the same ids.

However, it doesn't really matter. We will fix the coe.

**Comment by ldcouto** [comment] 2016-06-15 11:46
Fair enough. There's some priority on this since it's blocking the use of the validator. I can take over the task if you guys are too busy for it.

**Comment by CThuleHansen** [comment] 2016-06-15 11:47
That would be very much appreciated!

**Comment by ldcouto** [comment] 2016-06-15 11:48
Alright, I'm on it.

**Comment by ldcouto** [comment] 2016-06-21 14:15
All done. We have zero violations and the validator is invoked as part of the build. Should be trivial to keep violations to zero from now on.

**Closed** 2016-06-21 14:17 UTC
Labels: enhancement, → build
