### ISSUE TITLE
Download  manager in UI but does seem to unpack Overture

### ISSUE THREAD

**Issue by mpcagro** [into-cps/intocps-ui#149] opened 2016-08-29 21:23 UTC
The download manager does not seem to unpack Overture in download via the UI.
I am running Ubuntu 14.04, so I am unsure if it is related to my OS.
I would also expect Overture to start when I press the WaterTankController example model, but I am unsure if this was the intention.

**Comment by lausdahl** [comment] 2016-08-30 06:48
This is a duplicate of #144

**Closed by lausdahl** 2016-08-30 06:48 UTC
Labels: enhancement
