### ISSUE TITLE
Open Modelica download Corrupted file 

### ISSUE THREAD

**Issue by avh-agrointelli** [into-cps/intocps-ui#215] opened 2017-02-13 08:57 UTC
OpenModelica-v1.10.0-dev-440-gd0581ff-64bit is unreadable or corrupted

**Comment by CThuleHansen** [comment] 2017-02-13 13:09
I am also getting this error.

**Comment by adrpo** [comment] 2017-02-14 20:52
@CThuleHansen: the problem is that we generate new executables and then we remove older ones.
Do you support pointers to files without giving a md5 hash? I want to create a link to a file that changes.

**Comment by CThuleHansen** [comment] 2017-02-15 09:44
@adrpo when you create new executable just update the json with the new md5?

**Comment by adrpo** [comment] 2017-02-15 09:54
@CThuleHansen: yes, i will do that. Which is the latest json for the INTO-CPS app? 0.0.12.json or do you have something else for the developer version?

**Comment by ldcouto** [comment] 2017-02-15 09:56
Guys, are we sure it's a great idea to change executable without changing the bundle version?

@adrpo 12 is the latest release. 13 is already up in the development version

**Comment by adrpo** [comment] 2017-02-15 10:55
@ldcouto: you're right, but the problem is that the OM installer that 0.0.12 is pointing to is no longer available. From now on I will try to save aside the OM installers pointed by the INTO-CPS someplace for storage. I will update 0.0.12 and 0.0.13 with the needed installers.

**Comment by ldcouto** [comment] 2017-02-15 10:58
Great, thanks Adrian.

If it's too much work to save the installers, I think you can also remove them from the json entries. As long as the latest bundle has a valid download link, it should be fine.

**Comment by adrpo** [comment] 2017-02-15 12:09
The fix for 0.0.12 is in the PR here:
https://github.com/into-cps/into-cps.github.io/pull/8
where is the 0.0.13 json so I can fix that too?

**Comment by CThuleHansen** [comment] 2017-02-15 12:09
Switch to development branch, then you'll find it

**Comment by adrpo** [comment] 2017-02-15 12:10
ah, OK

**Comment by ldcouto** [comment] 2017-02-15 12:16
Closing this. Further work can be tracked on the PRs in the io repo.

@adrpo , thanks for quickly sorting this out.

**Comment by adrpo** [comment] 2017-02-15 12:17
Fixed also the "development" branch with:
https://github.com/into-cps/into-cps.github.io/pull/9

**Closed by ldcouto** 2017-02-15 12:16 UTC
Labels: bug
