### ISSUE TITLE
COE won't launch after reopening application

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#59] opened 2016-06-07 16:26 UTC
After the App crashed in bug #58 the COE will does not appear to launch. I assume I am to use the \COE Server Status' window to restart - this gives the message in attached screenshot. 

Not sure if this is a bug or not.
![screenshot 2016-06-07 17 23 20](https://cloud.githubusercontent.com/assets/5848867/15866006/eaae4100-2cd4-11e6-93ac-bc7d13046482.png)

**Comment by CThuleHansen** [comment] 2016-06-08 09:50
This will be fixed wednesday with the tools update.

**Comment by CThuleHansen** [comment] 2016-06-09 07:38
Duplicate of #60

**Closed by CThuleHansen** 2016-06-09 07:38 UTC
