### ISSUE TITLE
running coe on linux32 (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by astefano** [into-cps/intocps-ui#192] opened 2017-01-04 14:00 UTC
Hi,

Following the indications at http://into-cps.github.io/simulation/example.html, i've tried to 3 experiments running co-sim on:
- the case study line_follower_robot but the FMUs could not be loaded (see output_follower.txt [output_follower.txt](https://github.com/into-cps/intocps-ui/files/684789/output_follower.txt))
- an example i adapted from another source (the *.mo files i used are in the attachment: [springs.zip](https://github.com/into-cps/intocps-ui/files/684795/springs.zip)) for which i generated FMUs with: 
   * jmodelica but i get `org.intocps.orchestration.coe.AbortSimulationException: Invalid start condition the instances could not be created in: List({fmu1}.spring1, {fmu2}.spring2)` (see output_springs_jmodelica.txt [output_springs_jmodelica.txt](https://github.com/into-cps/intocps-ui/files/684788/output_springs_jmodelica.txt)
); is it that FMUs generated with jmodelica aren't supported?
   * openmodelica but i get `JSON object expected ',' or '}', got: "lineEnd":20,"colSta` (see output_springs_omodelica.txt [output_springs_omodelica.txt](https://github.com/into-cps/intocps-ui/files/684790/output_springs_omodelica.txt)); is it maybe an err in the FMU export from omodelica?

Just for the reference, i attach the json file as well (in the zip 
[config_springs.json.zip](https://github.com/into-cps/intocps-ui/files/684799/config_springs.json.zip))

Any clue on these issues?

Cheers,
Lacramioara

**Comment by ldcouto** [comment] 2017-01-04 17:10
Hi,

Thanks for reporting this. For the line follower, it could be that the 32bit binaries are missing. @richardpayne  can you look into this?

The jmodelica error does seem to be related to their export. @lausdahl , can you look at this? Would be good to know if we are supporting jmodelica or not.

It would be good to know what version of openmodelica was used. @adrpo can you check if there is indeed a problem?

**Comment by adrpo** [comment] 2017-01-04 17:32
For the line follower we only have 64bit windows FMUs, I'll make new ones containing Linux/Mac also.
In the case of springs it seems to be a bug in OM generation of support json files containing debug information. I'll have a look.

**Comment by ldcouto** [comment] 2017-01-04 17:48
That's great Adrian. Thanks.

**Comment by astefano** [comment] 2017-01-05 08:11
Thanks a lot Luis and Adrian for looking into this! 
Indeed, now that i check each of the fmus, LineFollower_Examples_SensorBlock1.fmu & 2 have only windows64 binaries, initially i looked only in the Body_block (which appeared in the error msg) but that one comes with a linux32 binary. Is LineFollower_Examples_SensorBlock1.fmu generated from the mo file from OM_Sensor/LineFollower/Examples?

**Comment by adrpo** [comment] 2017-01-05 08:19
Yes, the FMUs are generated from those Modelica files.

**Comment by astefano** [comment] 2017-01-05 08:19
also, for openmodelica, i generated the FMU with `translateModelFMU` from OMShell and the version i have is: 
`OMC version OpenModelica 1.11.0~dev-294-g505e2df`

**Comment by richardpayne** [comment] 2017-01-05 09:59
You will also find that the 3Danimation.FMU works in Windows only. There are non-3D multi-model configurations included in the example which omit the 3D view.

**Comment by lausdahl** [comment] 2017-01-13 22:52
Issue:

1. @adrpo please check that you do not place *.so files for 64 bit under 32 bit. It looks like you do that. See the error `wrong ELF class: ELFCLASS64error` 
2.
 * There seems to be an issue in the generated FMU. According to the standard this URI is valid: `file:/tmp/spring25593247481358409484/resources/` but the FMU complains and requests the authority to be present as well: `file:///absolute/path/resources` the FMU must support both formats according to FMI 2.0. We know others have challenges respecting that part of the standard too (Modelon FMI Toolbox for Matlab/Simuling) so we added a property you can set until this is fixed: `-Dfmi.instantiate.with.empty.authority=true`
 * looks like internal FMU stuff of the one being instantiated. I think Adrian already responded to this

**Comment by sjoelund** [comment] 2017-01-14 08:56
@lausdahl : I just checked all the 32-bit Linux builds for the given error, but the release (1.9.7), stable (1.11.0 beta2), and nightly (1.12.0-dev) all put a proper 32-bit binary in the linux32 directory. The 64-bit version puts files under the linux64 directory.

The [cross-compilation translateModelFMU](https://test.openmodelica.org/hudson/view/Linux/job/OpenModelica_TEST_SPECIAL/lastSuccessfulBuild/artifact/OpenModelica/testsuite/special/FmuExportCrossCompile/FmuExportCrossCompile-archive.fmu) also works properly:
```
$ file binaries/*/*.so binaries/*/*.dll binaries/*/*.dylib
binaries/arm-linux-gnueabihf/FmuExportCrossCompile.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=d452b0d748a8079718d96aef700d1fb7b7d26cba, not stripped
binaries/linux32/FmuExportCrossCompile.so:             ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=8f823f3d1e1e17d5bcceb899ca9c0f858b059b37, not stripped
binaries/linux64/FmuExportCrossCompile.so:             ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=19a4b1f3b099e13575e1a2534a0f820ba7c6d24b, not stripped
binaries/win32/FmuExportCrossCompile.dll:              PE32 executable (DLL) (console) Intel 80386, for MS Windows
binaries/win64/FmuExportCrossCompile.dll:              PE32+ executable (DLL) (console) x86-64, for MS Windows
binaries/darwin32/FmuExportCrossCompile.dylib:         Mach-O i386 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>
binaries/darwin64/FmuExportCrossCompile.dylib:         Mach-O 64-bit x86_64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>
```

If you can reproduce the error in an updated OMC (the given hash is 3 months old of a development branch) of any of the above software channels, I need:
* The OS and CPU of the system
* The version and source of the binary OMC (running the trusty package, Debian, etc?)
* The output of checkSettings() or `uname -a` (are you running 32-bit OMC on a 64-bit kernel confusing something?)
* The commands used to reproduce the error

**Comment by lausdahl** [comment] 2017-08-11 08:48
I'm closing this since no further information has been received. If we get the information then the issue can be re-opened.

**Closed by lausdahl** 2017-08-11 08:48 UTC
Labels: bug
