### ISSUE TITLE
INTO app crashes with black screen during simulation

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#58] opened 2016-06-07 16:20 UTC
I have tried simulating the line follower robot and the app crashes - the entire window goes black. The COE initialises, simulation starts and I see some variable updates in the livestream and then the crash occurs after approx. 30 seconds. I've attached a screenshot.

![screenshot 2016-06-07 17 16 39](https://cloud.githubusercontent.com/assets/5848867/15865832/2a1aa12c-2cd4-11e6-93b3-0381cb90d355.png)

**Comment by richardpayne** [comment] 2016-06-07 16:21
The java stopped working appears to be from the 3D FMU window.

**Comment by ldcouto** [comment] 2016-06-07 16:52
Can confirm. This happens with the water tank example as well.

**Comment by CThuleHansen** [comment] 2016-06-07 16:59
The 3D FMU is bugged and it is OpenGL related. This was mentioned in the WP4+5 net meeting 2016-06-01.

@richardpayne can you verify that it happens with the water tank example for you as well?

**Comment by CThuleHansen** [comment] 2016-06-07 17:00
And which version of the COE are you using?

**Comment by ldcouto** [comment] 2016-06-07 17:15
0.0.5-SNAPSHOT downloaded from http://overture.au.dk/into-cps/development/latest/

I cannot use the download manager work but I imagine Richard tried it.

**Comment by CThuleHansen** [comment] 2016-06-07 17:43
I have been able to reproduce it now. I will look into it tomorrow.

**Comment by lausdahl** [comment] 2016-06-07 19:00
Concerning the download manager:
- it uses normal http so I think it should work for all of us if the browser doesn't need a proxy
- the "release" uses a system specific way to store settings - it makes it a bit more complicated to locate. I know the location for mac but not for any other platform. (`/Users/USER_NAME/Library/Application Support/INTO-CPS APP/intoCpsApp/settings.json`
- if you had any other version of the app ever openen on your machine you need to delete the previous settings since the URLs for e.g. the update site, examples etc may have changed.

**Comment by lausdahl** [comment] 2016-06-07 19:06
I never get the *black* screen (which is *gray* on mac) when I build locally. However, I get it in `v1.0.0-rc` right after a simulation once it finishes. Skimming through the code, I found that the last thing the coe implementation does is to issue a project reload to make the browser pickup the `R_*` folder. 

See https://github.com/into-cps/intocps-ui/blob/master/src/coe/coe.ts#L264

maybe the project browser causes some king of problem on the reload event when a new file is present. (I tested with new multimodel which also triggers this event but it works as expected)

**Comment by ldcouto** [comment] 2016-06-07 19:09
I've had the error with local builds. Or do you mean when running with `npm
start` ?

**Comment by CThuleHansen** [comment] 2016-06-07 19:46
I am in the same position as Kenneth.
If the app is started using npm start in my "normal developer environment", then it works fine.
However when I use the release candidate the issue appears.

**Comment by ldcouto** [comment] 2016-06-07 20:05
Same here. npm start runs fine. gulp build black screens. Same on MacOS.

So, there is something clearly wrong with the packaged app. Any idea what?

**Comment by ldcouto** [comment] 2016-06-07 20:14
I don't think it's the simulation completed call back. Even if I suspend on it, after a while the app BSODs regardless.

**Comment by lausdahl** [comment] 2016-06-08 09:44
This is an issue with our dependencies and electron. We are upgrading to latest `1.2.1` it requires some modifications and is in progress in https://github.com/into-cps/intocps-ui/tree/electron-upgrade-1.2.1

We discovered that if we rebuild old versions which use to work the same issue applies due to the `^` use to match version of the dependencies. So we should replace this with a fixed version to avoid similar problems in the future.

**Comment by ldcouto** [comment] 2016-06-08 09:49
Alright, let me know when it's done and I'll announce a second RC. Should be safe to merge it into master direct. Nobody else should be working on it.

I guess we now know only Richard has used the app since nobody else complained.

**Comment by CThuleHansen** [comment] 2016-06-09 07:34
Fixed in https://github.com/into-cps/intocps-ui/commit/cdbdf1b713110af566ef92e9aeafdbd52940a7cc

**Closed by CThuleHansen** 2016-06-09 07:34 UTC
Labels: bug
